// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllSubCategories: typeof import('./src/views/category/component/AllSubCategories.vue')['default']
    FreshGoods: typeof import('./src/views/home/components/FreshGoods.vue')['default']
    GoodsBread: typeof import('./src/views/goods/components/GoodsBread.vue')['default']
    GoodsDetailPage: typeof import('./src/views/goods/GoodsDetailPage.vue')['default']
    GoodsImages: typeof import('./src/views/goods/components/GoodsImages.vue')['default']
    GoodsInfo: typeof import('./src/views/goods/components/GoodsInfo.vue')['default']
    GoodsItem: typeof import('./src/views/category/component/GoodsItem.vue')['default']
    GoodsList: typeof import('./src/views/category/component/GoodsList.vue')['default']
    GoodsSales: typeof import('./src/views/goods/components/GoodsSales.vue')['default']
    GoodsSku: typeof import('./src/views/goods/components/GoodsSku.vue')['default']
    HomeBanner: typeof import('./src/views/home/components/HomeBanner.vue')['default']
    HomeCategory: typeof import('./src/views/home/components/HomeCategory.vue')['default']
    HomeGoods: typeof import('./src/views/home/components/HomeGoods.vue')['default']
    HomePage: typeof import('./src/views/home/HomePage.vue')['default']
    HomePanel: typeof import('./src/views/home/components/HomePanel.vue')['default']
    HomeSkeleton: typeof import('./src/views/home/components/HomeSkeleton.vue')['default']
    HomeSpecial: typeof import('./src/views/home/components/HomeSpecial.vue')['default']
    HotBrands: typeof import('./src/views/home/components/HotBrands.vue')['default']
    HotRecommends: typeof import('./src/views/home/components/HotRecommends.vue')['default']
    RecommendsGoods: typeof import('./src/views/category/component/RecommendsGoods.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategoryBread: typeof import('./src/views/category/component/SubCategoryBread.vue')['default']
    SubCategoryFilter: typeof import('./src/views/category/component/SubCategoryFilter.vue')['default']
    SubCategoryPage: typeof import('./src/views/category/SubCategoryPage.vue')['default']
    SubCategorySort: typeof import('./src/views/category/component/SubCategorySort.vue')['default']
    TopCategoryBread: typeof import('./src/views/category/component/TopCategoryBread.vue')['default']
    TopcategoryPage: typeof import('./src/views/category/component/TopcategoryPage.vue')['default']
    TopCategoryPage: typeof import('./src/views/category/TopCategoryPage.vue')['default']
    XtxBread: typeof import('./src/components/XtxBread.vue')['default']
    XtxBreadItem: typeof import('./src/components/XtxBreadItem.vue')['default']
    XtxCarousel: typeof import('./src/components/XtxCarousel.vue')['default']
    XtxCheckbox: typeof import('./src/components/XtxCheckbox.vue')['default']
    XtxCity: typeof import('./src/components/XtxCity.vue')['default']
    XtxFooter: typeof import('./src/components/XtxFooter.vue')['default']
    XtxHeader: typeof import('./src/components/XtxHeader.vue')['default']
    XtxHeaderNav: typeof import('./src/components/XtxHeaderNav.vue')['default']
    XtxHeaderSticky: typeof import('./src/components/XtxHeaderSticky.vue')['default']
    XtxInfiniteLoading: typeof import('./src/components/XtxInfiniteLoading.vue')['default']
    XtxLayout: typeof import('./src/components/XtxLayout.vue')['default']
    XtxMore: typeof import('./src/components/XtxMore.vue')['default']
    XtxSkeleton: typeof import('./src/components/XtxSkeleton.vue')['default']
    XtxTopNav: typeof import('./src/components/XtxTopNav.vue')['default']
  }
}
